# Generated by Django 2.1 on 2018-08-21 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_auto_20180821_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_persons_name', models.CharField(max_length=100, verbose_name="Missing person's Name - കാണാതായ ആളുടെ പേര്")),
                ('missing_persons_age', models.CharField(max_length=100, verbose_name="Missing person's Age - കാണാതായ ആളുടെ പ്രായം")),
                ('missing_persons_gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], null=True, verbose_name="Missing person's Gender - കാണാതായ ആളുടെ ലിംഗം")),
                ('missing_persons_photo', models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_to, verbose_name="Missing person's Photo - കാണാതായ ആളുടെ ഫോട്ടോ ")),
                ('missing_from_district', models.CharField(choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15, verbose_name='Missing From District - ജില്ല')),
                ('missing_from_location', models.CharField(max_length=200, verbose_name='Missing From Location - സ്ഥലം')),
                ('missing_from_date', models.DateTimeField(verbose_name='Missing from (Date) - കാണാതായ ദിവസം')),
                ('missing_persons_description', models.TextField(verbose_name='Brief Description - കാണാതായ ആളുടെ ചെറു വിവരണം')),
                ('missing_persons_guardian', models.CharField(max_length=200, verbose_name="Father's/Guardiens's Name - കാണാതായ ആളുടെ പിതാവിന്റെ /രക്ഷിതാവിന്റെ പേര്")),
                ('missing_persons_address', models.TextField(verbose_name='Address - കാണാതായ ആളുടെ വിലാസം')),
                ('reported_by', models.CharField(max_length=100, verbose_name='Reported By - അറിയിക്കുന്ന ആളുടെ പേര്')),
                ('reporter_phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')], verbose_name="Reporter's Phone - അറിയിക്കുന്ന ആളുടെ ഫോണ്\u200d നമ്പര്\u200d")),
                ('relation_to_missing_person', models.CharField(max_length=100, verbose_name="Reporter's relation to missing person - കാണാതായ ആളുമായി അറിയിക്കുന്ന ആളുടെ ബന്ധം")),
                ('police_station', models.CharField(max_length=200, verbose_name='Police Station - പോലീസ് സ്റ്റേഷൻ ')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is active')),
                ('reported_on', models.DateTimeField(auto_now_add=True, verbose_name='Reported On - അറിയിച്ച ദിവസം')),
                ('found_on', models.DateTimeField(blank=True, null=True, verbose_name='Found On - കണ്ടെത്തിയ ദിവസം')),
                ('found_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Found At Location - കണ്ടെത്തിയ സ്ഥലം')),
                ('current_contact_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')], verbose_name='Current contact number - ഇപ്പോൾ ബന്ധപ്പെടാവുന്ന  ഫോണ്\u200d നമ്പര്\u200d')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Volunteer')),
            ],
        ),
    ]
