# Generated by Django 2.1 on 2018-08-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0069_auto_20180821_1929'),
        ('mainapp', '0069_missingperson'),
    ]

    operations = [
    ]
