# Generated by Django 2.1 on 2018-08-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0070_merge_20180821_2320'),
        ('mainapp', '0081_auto_20180823_1901'),
    ]

    operations = [
    ]
